### ISSUE TITLE
[Umbrella] Examples in real code

### ISSUE THREAD

**Issue by Abirdcfly** [Abirdcfly/dupword#3]
(Please feel free to add your changes!)

## Bug

- [x] https://github.com/istio/istio/pull/40706
- [x] https://github.com/ethereum/go-ethereum/pull/25618
- [x] https://github.com/influxdata/influxdb/pull/23685
- [x] https://github.com/minio/minio/pull/15607
- [x] https://github.com/kubernetes/minikube/pull/14882
- [x] https://github.com/etcd-io/etcd/pull/14405
- [x] https://github.com/etcd-io/etcd/pull/14390
- [x] https://github.com/prometheus/prometheus/pull/11225
- [x] https://github.com/rook/rook/pull/10827
- [x] https://github.com/argoproj/argo-cd/pull/10479
- [x] https://github.com/argoproj/argo-workflows/pull/9465
- [ ] https://github.com/kubernetes/ingress-nginx/pull/8995
- [x] https://github.com/kubevirt/kubevirt/pull/8377
- [x] https://github.com/containerd/containerd/pull/7338
- [x] https://github.com/thanos-io/thanos/pull/5660
- [x] https://github.com/grpc/grpc-go/pull/5616
- [x] https://github.com/coredns/coredns/pull/5592
- [x] https://github.com/cert-manager/cert-manager/pull/5413
- [x] https://github.com/vmware-tanzu/velero/pull/5261
- [x] https://github.com/dapr/dapr/pull/5099
- [x] https://github.com/caddyserver/caddy/pull/4986
- [x] https://github.com/kubeedge/kubeedge/pull/4147
- [x] https://github.com/spiffe/spire/pull/3377
- [x] https://github.com/goreleaser/goreleaser/pull/3347
- [x] https://github.com/fatedier/frp/pull/3081
- [ ] https://github.com/kubernetes-sigs/external-dns/pull/2986
- [x] https://github.com/junegunn/fzf/pull/2948
- [x] https://github.com/ent/ent/pull/2892
- [x] https://github.com/evanw/esbuild/pull/2502
- [x] https://github.com/volcano-sh/volcano/pull/2470
- [x] https://github.com/GoogleContainerTools/kaniko/pull/2232
- [x] https://github.com/jesseduffield/lazygit/pull/2143
- [ ] https://github.com/cue-lang/cue/pull/1895
- [x] https://github.com/mikefarah/yq/pull/1322
- [x] https://github.com/github/gh-ost/pull/1175
- [x] https://github.com/uber-go/zap/pull/1169
- [x] https://github.com/onsi/ginkgo/pull/1028
- [ ] https://github.com/Netflix/chaosmonkey/pull/76

## some releated issue

- [x] https://github.com/golang/go/issues/54740 and ~~Trying to fix [CL 426594](https://go-review.googlesource.com/c/tools/+/426594)~~ has been fixed by [CL 426734](https://go-review.googlesource.com/c/tools/+/426734/), just wait a new release.
- [x] https://github.com/golang/go/issues/54774 and has been fixed by [CL 426654](https://go-review.googlesource.com/c/tools/+/426654)
- [x] https://github.com/golang/go/issues/54789 not a bug, will not fix

**Comment by Abirdcfly** [comment]
The above example is enough to show that the wrong duplicate word problem exists in a large number of open source go projects, and if a pull request can be proposed to fix the problem, the probability is that the pull request will be merged.

So just close this issue.
